apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platformx-finops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platformx
  source:
    repoURL: https://github.com/reusaymane/platformx-finops
    targetRevision: main
    path: gitops/argocd/apps/envs/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
