replicaCount: 1

image:
  repository: platformx-finops_data-collector
  pullPolicy: Never
  tag: "latest"

env:
  COLLECT_INTERVAL: "60s"
  FAKE_MODE: "true"
  AWS_REGION: "eu-west-3"
  LOG_LEVEL: "info"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
